import type { Agent, FileChange } from "./types";

/** Build an added-file patch whose counts are coherent with its own lines. */
function addedFile(path: string, lines: readonly string[]): FileChange {
  const body = lines.join("\n");
  return {
    path,
    additions: lines.length,
    deletions: 0,
    kind: "added",
    newFile: { content: body },
    hunks: [
      `--- /dev/null\n+++ b/${path}\n@@ -0,0 +1,${lines.length} @@\n${lines.map((line) => `+${line}`).join("\n")}`,
    ],
  };
}

const appLines = [
  "import { AnimatePresence, motion } from \"motion/react\";",
  "import { useEffect, useMemo, useState } from \"react\";",
  "import { initialAgents } from \"./fixtures\";",
  "",
  "export function App() {",
  "  const [drawer, setDrawer] = useState<Drawer | null>(\"focus\");",
  "  const [selectedId, setSelectedId] = useState(\"lead\");",
  "  const [replyOpen, setReplyOpen] = useState(false);",
  "",
  "  const selected = agents.find((agent) => agent.id === selectedId);",
  "",
  "  return (",
  "    <main className=\"hud-root\">",
  "      <div className=\"hud\" data-edge={edge}>",
  "        <Constellation selected={selected} />",
  "      </div>",
  "    </main>",
  "  );",
  "}",
];

const styleLines = [
  ":root {",
  "  --base: #303446;",
  "  --paper: #292c3c;",
  "  --ink: #c6d0f5;",
  "  --accent: #babbf1;",
  "  --good: #a6d189;",
  "  --ember: #e78284;",
  "}",
  "",
  ".hud {",
  "  position: absolute;",
  "  bottom: 0;",
  "  left: 50%;",
  "  transform: translateX(-50%);",
];

const shellLines = [
  "import AppKit",
  "import WebKit",
  "",
  "final class FloatingPanel: NSPanel {",
  "  override var canBecomeKey: Bool { true }",
  "  override var canBecomeMain: Bool { false }",
  "}",
  "",
  "let application = NSApplication.shared",
  "let delegate = AppDelegate()",
  "application.delegate = delegate",
  "application.positionStage()",
  "application.run()",
];

export const initialAgents: readonly Agent[] = [
  {
    id: "lead",
    name: "Synthesis lead",
    role: "Coordinator",
    task: "Shape the smallest useful agent development environment",
    status: "working",
    provider: "Claude Code",
    model: "Opus",
    elapsed: "18m",
    messages: [
      {
        id: "lead-1",
        role: "human",
        body: "Explore the smallest useful ADE. Keep it beautiful, extensible and calm.",
        time: "10:42",
      },
      {
        id: "lead-2",
        role: "agent",
        body: "I split the problem into interaction, native shell and orchestration boundaries. Three workers are active; the interaction prototype is furthest along.",
        time: "10:57",
      },
    ],
    changes: [],
  },
  {
    id: "interaction",
    parentId: "lead",
    name: "Interaction study",
    role: "Product designer",
    task: "Test focused constellation against a strong session list",
    status: "done",
    provider: "Codex",
    model: "GPT-5",
    elapsed: "12m",
    messages: [
      {
        id: "interaction-1",
        role: "agent",
        body: "The constellation works when it stays local: selected Agent, parent and direct children only. The global graph fails at portfolio scale.",
        time: "10:54",
      },
    ],
    result:
      "Use a focused constellation as navigation, not as the durable information model. Always provide search and a compact fleet list as escape hatches.",
    changes: [],
  },
  {
    id: "prototype",
    parentId: "lead",
    name: "Floating prototype",
    role: "Interface engineer",
    task: "Build the AppKit and WebKit interaction proof",
    status: "working",
    provider: "OpenCode",
    model: "Union Alpha",
    elapsed: "9m",
    messages: [
      {
        id: "prototype-1",
        role: "agent",
        body: "The panel shell is working. I’m tuning focus, translucency and the transition between the constellation and conversation detail.",
        time: "10:59",
      },
    ],
    changes: [
      addedFile("src/App.tsx", appLines),
      addedFile("src/styles.css", styleLines),
      addedFile("Sources/HeedShell/main.swift", shellLines),
    ],
  },
  {
    id: "runtime",
    parentId: "lead",
    name: "Runtime boundary",
    role: "Systems architect",
    task: "Define spawn, wait and result without rebuilding Herdr",
    status: "waiting",
    provider: "Pi",
    model: "Sonnet",
    elapsed: "15m",
    attention: "One decision",
    messages: [
      {
        id: "runtime-1",
        role: "agent",
        body: "Should result handoff be a required explicit artifact, or may a provider adapter expose the final response when available?",
        time: "11:01",
      },
    ],
    changes: [],
  },
  {
    id: "review",
    parentId: "lead",
    name: "Scope challenger",
    role: "Adversarial reviewer",
    task: "Find where the minimal product is already becoming an IDE",
    status: "needs-you",
    provider: "Codex",
    model: "GPT-5",
    elapsed: "7m",
    attention: "Review ready",
    messages: [
      {
        id: "review-1",
        role: "agent",
        body: "The current boundary is coherent, but a built-in diff viewer is the first likely source of IDE creep. I left a short recommendation.",
        time: "11:03",
      },
    ],
    result:
      "Keep changed-file evidence in the core UI, but open rich diffs in an extension or the user’s preferred review tool. Do not add editing.",
    changes: [],
  },
  {
    id: "motion",
    parentId: "prototype",
    name: "Motion language",
    role: "Interaction specialist",
    task: "Tune recentering and spatial continuity",
    status: "done",
    provider: "Claude Code",
    model: "Sonnet",
    elapsed: "5m",
    messages: [
      {
        id: "motion-1",
        role: "agent",
        body: "Recentring should preserve direction: the selected child moves inward while its former parent retreats to the left edge.",
        time: "11:04",
      },
    ],
    result: "Use restrained spring motion and preserve the parent’s direction during every focus transition.",
    changes: [],
  },
  {
    id: "shell",
    parentId: "prototype",
    name: "Native shell",
    role: "macOS engineer",
    task: "Make the interface feel summoned rather than launched",
    status: "failed",
    provider: "OpenCode",
    model: "Union Alpha",
    elapsed: "3m",
    attention: "Needs retry",
    messages: [
      {
        id: "shell-1",
        role: "agent",
        body: "The first global shortcut collided with Spotlight. I recommend Option+Space for the proof of concept.",
        time: "11:05",
      },
    ],
    changes: [],
  },
  ...(
    [
      ["payments", undefined, "Payments migration", "Coordinator", "Move billing events onto the new ledger", "working", "Claude Code", "Opus", "34m", undefined, "ledger"],
      ["payments-schema", "payments", "Schema audit", "Data engineer", "Compare production events against the v3 contract", "done", "Codex", "GPT-5", "18m", undefined, "ledger"],
      ["payments-backfill", "payments", "Backfill worker", "Backend engineer", "Implement resumable event replay", "working", "Claude Code", "Sonnet", "22m", undefined, "ledger"],
      ["payments-review", "payments", "Migration review", "Reviewer", "Check idempotency and rollback guarantees", "needs-you", "Codex", "GPT-5", "11m", "2 comments", "ledger"],
      ["payments-load", "payments-backfill", "Load test", "Performance engineer", "Exercise the replay path with production-shaped data", "waiting", "OpenCode", "Union Alpha", "8m", undefined, "ledger"],
      ["mobile", undefined, "Mobile polish", "Coordinator", "Prepare the September iOS release candidate", "needs-you", "Claude Code", "Opus", "27m", "Choose build", "ios-app"],
      ["mobile-crashes", "mobile", "Crash triage", "iOS engineer", "Resolve the top three launch regressions", "working", "Codex", "GPT-5", "16m", undefined, "ios-app"],
      ["mobile-copy", "mobile", "Release copy", "Product writer", "Draft concise App Store release notes", "done", "Claude Code", "Haiku", "6m", undefined, "ios-app"],
      ["mobile-snapshots", "mobile", "Snapshot refresh", "Test engineer", "Update visual baselines for the new navigation", "failed", "OpenCode", "Union Alpha", "13m", "Retry", "ios-app"],
      ["search", undefined, "Search relevance", "Coordinator", "Improve ranking for short ambiguous queries", "working", "Codex", "GPT-5", "41m", undefined, "search"],
      ["search-eval", "search", "Evaluation set", "Research engineer", "Build a balanced set of failed real-world queries", "done", "Claude Code", "Sonnet", "24m", undefined, "search"],
      ["search-ranker", "search", "Ranker experiment", "ML engineer", "Compare reciprocal rank fusion with the current scorer", "working", "Codex", "GPT-5", "19m", undefined, "search"],
      ["search-analysis", "search", "Failure analysis", "Analyst", "Cluster regressions and identify dominant failure modes", "waiting", "Pi", "Sonnet", "9m", undefined, "search"],
      ["auth", undefined, "Authentication cleanup", "Coordinator", "Remove the legacy session path", "waiting", "Claude Code", "Opus", "52m", undefined, "platform"],
      ["auth-cookies", "auth", "Cookie inventory", "Security engineer", "Trace every writer of the legacy cookie", "done", "Codex", "GPT-5", "14m", undefined, "platform"],
      ["auth-api", "auth", "Token endpoint", "Backend engineer", "Move refresh handling behind the gateway", "needs-you", "Claude Code", "Sonnet", "26m", "Approve scope", "platform"],
      ["auth-docs", "auth", "Migration notes", "Technical writer", "Document client migration and rollback", "working", "OpenCode", "Union Alpha", "7m", undefined, "platform"],
      ["heed-design", undefined, "Heed map", "Coordinator", "Refine map-to-session continuity", "working", "Claude Code", "Opus", "1h 08m", undefined, "heed"],
      ["heed-focus", "heed-design", "Focus transition", "Interface engineer", "Preserve camera and selection across workbench entry", "working", "Codex", "GPT-5", "31m", undefined, "heed"],
      ["heed-host", "heed-design", "Herdr adapter", "Systems engineer", "Harden pane discovery and session attachment", "needs-you", "Claude Code", "Sonnet", "17m", "Review patch", "heed"],
      ["heed-tests", "heed-design", "Browser regressions", "Test engineer", "Cover focus, resize and companion reconnect", "done", "OpenCode", "Union Alpha", "12m", undefined, "heed"],
      ["docs", undefined, "Documentation sweep", "Coordinator", "Bring setup guidance in line with the current CLI", "done", "Codex", "GPT-5", "38m", undefined, "developer-docs"],
      ["docs-install", "docs", "Install guide", "Technical writer", "Simplify first-run setup and troubleshooting", "done", "Claude Code", "Sonnet", "15m", undefined, "developer-docs"],
      ["docs-examples", "docs", "Example refresh", "Developer advocate", "Replace stale examples with runnable projects", "failed", "OpenCode", "Union Alpha", "21m", "Missing fixture", "developer-docs"],
      ["ops", undefined, "Release watch", "Coordinator", "Monitor deployment and investigate anomalies", "waiting", "Pi", "Sonnet", "2h 14m", undefined, "operations"],
      ["ops-errors", "ops", "Error budget", "SRE", "Compare the canary against the previous release", "working", "Codex", "GPT-5", "29m", undefined, "operations"],
    ] as const
  ).map(([id, parentId, name, role, task, status, provider, model, elapsed, attention, workspace]) => ({
    id,
    ...(parentId ? { parentId } : {}),
    name,
    role,
    task,
    status,
    provider,
    model,
    elapsed,
    ...(attention ? { attention } : {}),
    workspace,
    messages: [],
    changes: [],
  } satisfies Agent)),
];
